config/routes.rb
Rails.application.routes.draw do
  #クレジットカード登録
  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
    end
  end

  devise_for :users
  root "items#index"
  get "items/item"
  resources :signups, only: [:create] do
    collection do
      get "registration"
      get "newmember"
      get "phonenumber"
      get "authentication"
      get "address"
      get "payment"
      get "completion"
      post 'pay'
    end
  end

  resources :items,only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    # get "items/item"
    get "items/bought"
    get "items/purchase"
  
    get "items/search"
    get "items/buy"
    get "items/transaction"
    
    member do
      get 'select'
    end
    collection do
      get 'search'
    end
    resources :purchases, only: [:index, :show] do
      member do
      end
      collection do
        post 'pay', to: 'purchases#pay'
        get 'buy', to: 'purchases#buy'
      end
    end
  end
      
  resources :categories, only: [:show, :index]

  resources :users, only: [:show] do
    member do

    end
    collection do 
      get 'card_add_btn'
      get 'card_delete_btn'
      get 'card_input_info'
      get 'create'
      get 'information'
      get 'logout'
      get 'mypage'
      get 'profile'  
      get 'seller_selling'
      get 'seller_trading'
      get 'seller_sold'
    end
  end

  

end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_action :validates_newmember, only: :phonenumber # step1のバリデーション
  before_action :validates_phonenumber, only: :authentication # step2のバリデーション
  before_action :validates_authentication, only: :address # step3のバリデーション
  before_action :validates_address, only: :create  # step4のバリデーション
  # before_action :validates_payment, only: :create # step5のバリデーション
  ########## ↑上文はバリデーション検討中のためコメントアウト #############
  def registration
  end

  def newmember
    @user = User.new # 新規のインスタンスを作成
  end

  def phonenumber
    @user = User.new
  end

  def authentication
    @user = User.new
  end

  def address
    @user = User.new
  end

  def create
    @user = User.new(
    # sessionに保存された値をインスタンスに渡す
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      last_name: session[:last_name],
      first_name: session[:first_name],
      last_name_kana: session[:last_name_kana],
      first_name_kana: session[:first_name_kana],
      birthdate_year: session[:birthdate_year],
      birthdate_month: session[:birthdate_month],
      birthdate_day: session[:birthdate_day],
      phone_number: session[:phone_number],
      authentication_code: session[:authentication_code],
      address_last_name: session[:address_last_name],
      address_first_name: session[:address_first_name],
      address_last_name_kana: session[:address_last_name_kana],
      address_first_name_kana: session[:address_first_name_kana],
      postal_code: session[:postal_code],
      prefecture: session[:prefecture],
      city: session[:city],
      block_number: session[:block_number],
      building_name: session[:building_name],
      home_phone_number: session[:home_phone_number],
    )

    
    if @user.save
      # ログイン状態維持のためuser_idをsessionに保存
      session[:user_id] = @user.id
      redirect_to '/signups/payment'
    else
      render '/signups/address'
    end
  end

  def payment
    @card = Card.new
  end

  # 登録画面で入力した情報をDBに保存
  def pay
    Payjp.api_key = "sk_test_9629ac740599209dbad72f1b"
    if params['payjp-token'].blank?
      redirect_to action: "payment"
    else
      customer = Payjp::Customer.create( # ここで先ほど生成したトークンを顧客情報と紐付け、PAY.JP管理サイトに送信
        card: params['payjp-token'],
      )
      @card = Card.new(user_id: session[:user_id], customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "completion"
      else
        redirect_to action: "payment"
        flash[:alert] = 'クレジットカード登録に失敗しました'
      end
    end
  end

  def completion
    # sign_inメソッドを使いcreateアクションで作成・保存したデータのidを用いてサインイン
    sign_in User.find(session[:user_id]) unless user_signed_in?
  end

  
  private
  # ストロングパラメーターで許可するキーを設定する
  def user_params
    params.require(:user).permit(
      :nickname,
      :email,
      :password,
      :password_confirmation,
      :last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :birthdate_year,
      :birthdate_month,
      :birthdate_day,
      :phone_number,
      :authentication_code,
      :address_last_name,
      :address_first_name,
      :address_last_name_kana,
      :address_first_name_kana,
      :postal_code,
      :prefecture,
      :city,
      :block_number,
      :building_name,
      :home_phone_number,
    )
  end
  
  def validates_newmember
      # newmemberで入力された値をsessionに保存
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:last_name] = user_params[:last_name]
    session[:first_name] = user_params[:first_name]
    session[:last_name_kana] = user_params[:last_name_kana]
    session[:first_name_kana] = user_params[:first_name_kana]
    session[:birthdate_year] = user_params[:birthdate_year]
    session[:birthdate_month] = user_params[:birthdate_month]
    session[:birthdate_day] = user_params[:birthdate_day]
    @user = User.new( # 新規のインスタンスを作成
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      last_name: session[:last_name],
      first_name: session[:first_name],
      last_name_kana: session[:last_name_kana],
      first_name_kana: session[:first_name_kana],
      birthdate_year: session[:birthdate_year],
      birthdate_month: session[:birthdate_month],
      birthdate_day: session[:birthdate_day],
      # 入力前の情報は、バリデーションに通る値を仮で入れる
      phone_number: "08000000000",
      authentication_code: "123456",
      address_last_name: "山田",
      address_first_name: "太郎",
      address_last_name_kana: "ヤマダ",
      address_first_name_kana: "タロウ",
      postal_code: "000-0000",
      prefecture: "千葉県",
      city: "千葉市",
      block_number: "若葉区1-1-1",
    )
    render '/signups/newmember' unless @user.valid?
  end
  
  def validates_phonenumber
    session[:phone_number] = user_params[:phone_number]
    
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      last_name: session[:last_name],
      first_name: session[:first_name],
      last_name_kana: session[:last_name_kana],
      first_name_kana: session[:first_name_kana],
      birthdate_year: session[:birthdate_year],
      birthdate_month: session[:birthdate_month],
      birthdate_day: session[:birthdate_day],
      phone_number: session[:phone_number],
      
      authentication_code: "123456",
      address_last_name: "山田",
      address_first_name: "太郎",
      address_last_name_kana: "ヤマダ",
      address_first_name_kana: "タロウ",
      postal_code: "000-0000",
      prefecture: "千葉県",
      city: "千葉市",
      block_number: "若葉区1-1-1",
    )
    render '/signups/phonenumber' unless @user.valid?
  end

  def validates_authentication
    # authenticationで入力された値をsessionに保存
    session[:authentication_code] = user_params[:authentication_code]
    
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      last_name: session[:last_name],
      first_name: session[:first_name],
      last_name_kana: session[:last_name_kana],
      first_name_kana: session[:first_name_kana],
      birthdate_year: session[:birthdate_year],
      birthdate_month: session[:birthdate_month],
      birthdate_day: session[:birthdate_day],
      phone_number: session[:phone_number],
      authentication_code: session[:authentication_code],

      address_last_name: "山田",
      address_first_name: "太郎",
      address_last_name_kana: "ヤマダ",
      address_first_name_kana: "タロウ",
      postal_code: "000-0000",
      prefecture: "千葉県",
      city: "千葉市",
      block_number: "若葉区1-1-1",
      building_name: "yamadaビル",
      home_phone_number: "09000000000",
    )
    render '/signups/authentication' unless @user.valid?
  end

  def validates_address
    # addressで入力された値をsessionに保存
    session[:address_last_name] = user_params[:address_last_name]
    session[:address_first_name] = user_params[:address_first_name]
    session[:address_last_name_kana] = user_params[:address_last_name_kana]
    session[:address_first_name_kana] = user_params[:address_first_name_kana]
    session[:postal_code] = user_params[:postal_code]
    session[:prefecture] = user_params[:prefecture]
    session[:city] = user_params[:city]
    session[:block_number] = user_params[:block_number]
    session[:building_name] = user_params[:building_name]
    session[:home_phone_number] = user_params[:home_phone_number]
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      last_name: session[:last_name],
      first_name: session[:first_name],
      last_name_kana: session[:last_name_kana],
      first_name_kana: session[:first_name_kana],
      birthdate_year: session[:birthdate_year],
      birthdate_month: session[:birthdate_month],
      birthdate_day: session[:birthdate_day],
      phone_number: session[:phone_number],
      authentication_code: session[:authentication_code],
      address_last_name: session[:address_last_name],
      address_first_name: session[:address_first_name],
      address_last_name_kana: session[:address_last_name_kana],
      address_first_name_kana: session[:address_first_name_kana],
      postal_code: session[:postal_code],
      prefecture: session[:prefecture],
      city: session[:city],
      block_number: session[:block_number],
      building_name: session[:building_name],
      home_phone_number: session[:home_phone_number],
    )
    render '/signups/address' unless @user.valid?
  end
 ######################################################################
  # def validates_payment
  #   session[:card_number] = user_params[:card_number]
  #   session[:card_expiration_date_month] = user_params[:card_expiration_date_month]
  #   session[:card_expiration_date_year] = user_params[:card_expiration_date_year]
  #   session[:card_security_code] = user_params[:card_security_code]
  #   @user = User.new(
  #   # sessionに保存された値をインスタンスに渡す
  #     nickname: session[:nickname],
  #     email: session[:email],
  #     password: session[:password],
  #     password_confirmation: session[:password_confirmation],
  #     last_name: session[:last_name],
  #     first_name: session[:first_name],
  #     last_name_kana: session[:last_name_kana],
  #     first_name_kana: session[:first_name_kana],
  #     birthdate_year: session[:birthdate_year],
  #     birthdate_month: session[:birthdate_month],
  #     birthdate_day: session[:birthdate_day],

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/signups/_address_bar.html.haml
%header.single-header
  %h1
    =link_to "/items/index" do
      %img(src="//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?2296184308" alt="mercari")
  %nav.progress-bar.signup-bar
    %ol.clearfix
      %li
        会員情報
        .progress-status-first-red-line
      %li
        電話番号認証
        .progress-status-second-red-line
      %li.active
        お届け先住所入力
        .progress-status-third
      %li
        支払い方法
        .progress-status
      %li
        完了
        .progress-status-last

app/views/signups/_error-messages.html.haml
- if user.errors.any?
  - unless user.valid?
    - if errors = user.errors.full_messages_for(column.to_sym)
      %ul.form-group__has-error-text
        - errors.each do |error|
          %li= error

app/views/signups/authentication.html.haml
.signups-body
  .single-container
    = render 'authentication_bar'
    %main.single-main
      %section.l-single-container
        %h2.l-single-head.registration
          電話番号認証
        = form_with model: @user, local: true, url: address_signups_path, method: :get, class: "l-single-inner registration-form", novalidate: 'novalidate' do |f|
          .l-single-content
            .form-group
              = f.label :authentication_code, "認証番号"
              - if @user.errors.full_messages_for(:authentication_code).any?
                = f.number_field :authentication_code, placeholder: '認証番号を入力', class: 'input-default--has-error'
              - else
                = f.number_field :authentication_code, placeholder: '認証番号を入力', class: 'input-default'
              = render partial: 'error-messages', locals: { user: @user, column: "authentication_code"}
              %p
                SMSで届いた認証番号を入力してください
            = f.submit '認証して完了', class: "btn-default btn-red"
        %form.l-single-inner.registration-form{action: "https://www.mercari.com/jp/signup/sms_confirmation/", method: "POST", novalidate: "novalidate"}
          %input{type: "hidden", value: "", name: "after_save_callback"}
          .l-single-content
            .form-group
              %h3.text-left.l-chapter-sub-head
                30秒たっても認証番号が届かない方へ
              %p
                電話で認証番号を聞く事もできます。
            =link_to root_path, class: "btn-default btn-red" do
              電話で認証番号を聞く(通話無料)
        %form.l-single-inner.registration-form{action: "https://www.mercari.com/jp/signup/sms_confirmation/", method: "POST", novalidate: "novalidate"}
          %input{type: "hidden", value: "", name: "after_save_callback"}
          .l-single-content
            .form-group
              %h3.text-left.l-chapter-sub-head
                認証番号を再送することもできます。もう一度電話番号を入力して下さい。
              %p.l-single-text
                =link_to "#", target: "_blank" do
                  電話番号を再度入力する
              %p.l-single-text.text-center
                ※SMSが届かない場合は
                =link_to "#", target: "_blank" do
                  SMS受信設定
                を確認して、もう一度電話番号を入力してくださいしてください。
    = render 'registration_footer'

app/views/signups/newmember.html.haml
.signups-body
  .single-container	
    = render 'newmember_bar'
    %main.single-main
      %section.l-single-container
        %h2.l-single-head.registration
          会員情報入力
        = form_with model: @user, local: true, url: phonenumber_signups_path, method: :get, class: "l-single-inner registration-form", novalidate: 'novalidate' do |f|
          .l-single-content
            .form-group
              = f.label :nickname, "ニックネーム"
              %sapn.form-require
                必須
              - if @user.errors.full_messages_for(:nickname).any?
                = f.text_field :nickname, placeholder: "例) メルカリ太郎", class: "input-default--has-error"
              - else
                = f.text_field :nickname, placeholder: "例) メルカリ太郎", class: "input-default"
              = render partial: 'error-messages', locals: { user: @user, column: "nickname"}
            .form-group
              = f.label :email, "メールアドレス"
              %sapn.form-require
                必須
              - if @user.errors.full_messages_for(:email).any?
                = f.email_field :email, placeholder: 'PC・携帯どちらでも可', class: 'input-default--has-error'
              - else
                = f.email_field :email, placeholder: 'PC・携帯どちらでも可', class: 'input-default'
              = render partial: 'error-messages', locals: { user: @user, column: "email"}
            .form-group
              = f.label :password, "パスワード"
              %sapn.form-require
                必須
              - if @user.errors.full_messages_for(:password).any?
                = f.password_field :password, placeholder: '7文字以上', class: 'input-default--has-error'
              - else
                = f.password_field :password, placeholder: '7文字以上', class: 'input-default'
              = render partial: 'error-messages', locals: { user: @user, column: "password"}
            .form-group
              = f.label :password2, "パスワード(確認)"
              %sapn.form-require
                必須
              - if @user.errors.full_messages_for(:password_confirmation).any?
                = f.password_field :password_confirmation, placeholder: '7文字以上', class: 'input-default--has-error'
              - else
                = f.password_field :password_confirmation, placeholder: '7文字以上', class: 'input-default'
              = render partial: 'error-messages', locals: { user: @user, column: "password_confirmation"}
            .form-group
              %h3.text-left.l-chapter-sub-head
                本人確認
              %p.l-single-text
                安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
            .form-group
              %div
                = f.label :name, "お名前(全角)"
                %sapn.form-require
                  必須
              - if @user.errors.full_messages_for(:last_name).any?
                = f.text_field :last_name, placeholder: "例) 山田", class: "input-default--has-error half"
              - else
                = f.text_field :last_name, placeholder: "例) 山田", class: "input-default half"
              - if @user.errors.full_messages_for(:first_name).any?
                = f.text_field :first_name, placeholder: "例) 彩", class: "input-default--has-error half"
              - else
                = f.text_field :first_name, placeholder: "例) 彩", class: "input-default half"
              = render partial: 'error-messages', locals: { user: @user, column: "last_name"}
              = render partial: 'error-messages', locals: { user: @user, column: "first_name"}
            .form-group
              %div
                = f.label :name_kana, "お名前(カナ)"
                %sapn.form-require
                  必須
              - if @user.errors.full_messages_for(:last_name_kana).any?
                = f.text_field :last_name_kana, placeholder: '例) ヤマダ', class: 'input-default--has-error half'
              - else
                = f.text_field :last_name_kana, placeholder: '例) ヤマダ', class: 'input-default half'
              - if @user.errors.full_messages_for(:first_name_kana).any?
                = f.text_field :first_name_kana, placeholder: '例) アヤ', class: 'input-default--has-error half'
              - else
                = f.text_field :first_name_kana, placeholder: '例) アヤ', class: 'input-default half'
              = render partial: 'error-messages', locals: { user: @user, column: "last_name_kana"}
              = render partial: 'error-messages', locals: { user: @user, column: "first_name_kana"}
            .form-group
              = f.label :birthdate, "生年月日"
              %sapn.form-require
                必須
              %br/
              .birthday-select-wrap
                .select-wrap
                  = fa_icon 'chevron-down'
                  - if @user.errors.full_messages_for(:birthdate_year).any?
                    = f.select :birthdate_year, [2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990,1989,1988,1987,1986,1985,1984,1983,1982,1981,1980,1979,1978,1977,1976,1975,1974,1973,1972,1971,1970,1969,1968,1967,1966,1965,1964,1963,1962,1961,1960,1959,1958,1957,1956,1955,1954,1953,1952,1951,1950,1949,1948,1947,1946,1945,1944,1943,1942,1941,1940,1939,1938,1937,1936,1935,1934,1933,1932,1931,1930,1929,1928,1927,1926,1925,1924,1923,1922,1921,1920,1919,1918,1917,1916,1915,1914,1913,1912,1911,1910,1909,1908,1907,1906,1905,1904,1903,1902,1901,1900] ,{prompt: "--"}, class: "select-default--has-error"
                  - else
                    = f.select :birthdate_year, [2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990,1989,1988,1987,1986,1985,1984,1983,1982,1981,1980,1979,1978,1977,1976,1975,1974,1973,1972,1971,1970,1969,1968,1967,1966,1965,1964,1963,1962,1961,1960,1959,1958,1957,1956,1955,1954,1953,1952,1951,1950,1949,1948,1947,1946,1945,1944,1943,1942,1941,1940,1939,1938,1937,1936,1935,1934,1933,1932,1931,1930,1929,1928,1927,1926,1925,1924,1923,1922,1921,1920,1919,1918,1917,1916,1915,1914,1913,1912,1911,1910,1909,1908,1907,1906,1905,1904,1903,1902,1901,1900] ,{prompt: "--"}, class: "select-default"
                %span 年
                .select-wrap.select-wrap__month
                  = fa_icon 'chevron-down'
                  - if @user.errors.full_messages_for(:birthdate_month).any?
                    = f.select :birthdate_month, [1,2,3,4,5,6,7,8,9,10,11,12],{prompt: "--"}, class: "select-default--has-error"
                  - else
                    = f.select :birthdate_month, [1,2,3,4,5,6,7,8,9,10,11,12],{prompt: "--"}, class: "select-default"
                %span 月
                .select-wrap.select-wrap__day
                  = fa_icon 'chevron-down'
                  - if @user.errors.full_messages_for(:birthdate_day).any?
                    = f.select :birthdate_day, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],{prompt: "--"}, class: "select-default--has-error"
                  - else
                    = f.select :birthdate_day, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],{prompt: "--"}, class: "select-default"
                %span 日
                = render partial: 'error-messages', locals: { user: @user, column: "birthdate_year"}
                = render partial: 'error-messages', locals: { user: @user, column: "birthdate_month"}
                = render partial: 'error-messages', locals: { user: @user, column: "birthdate_day"}
              .clearfix
              %p.form-info-text
                ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
          .l-single-content
            .form-group
              .g-recaptcha.signup-recaptcha{"data-sitekey": "6LfZGCYTAAAAAHoK-s7Lg5OdYg5Fq4susvALmZoc"}
                %div{style: "width: 304px; height: 78px;"}
                  %div
                    %iframe{frameborder: "0", height: "78", name: "a-nz28pqy6hu5s", role: "presentation", sandbox: "allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox", scrolling: "no", src: "https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LfZGCYTAAAAAHoK-s7Lg5OdYg5Fq4susvALmZoc&co=aHR0cHM6Ly93d3cubWVyY2FyaS5jb206NDQz&hl=ja&v=Zy-zVXWdnDW6AUZkKlojAKGe&size=normal&cb=mvaapz42k0rb", width: "304"}
                  %textarea#g-recaptcha-response.g-recaptcha-response{name: "g-recaptcha-response", style: "width: 250px; height: 40px; border: 1px solid rgb(193, 193, 193); margin: 10px 25px; padding: 0px; resize: none; display: none;"}
            .form-group
              %p.l-single-text.text-center
                「次へ進む」のボタンを押すことにより、
                =link_to "https://www.mercari.com/jp/tos_list", target: "_blank" do
                  利用規約
                に同意したものとみなします
            = f.submit '次へ進む', class: "btn-default btn-red"
            .form-group.text-right
              %p
                =link_to "https://www.mercari.com/jp/help_center/article/423", target: "_blank" do
                  本人情報の登録について
                  = fa_icon 'chevron-right'
    = render 'registration_footer'

app/views/signups/payment.html.haml
.signups-body
  .single-container
    = render 'payment_bar'
    %main.single-main
      %section.l-single-container
        %h2.l-single-head.registration
          支払い方法
        = form_with model: @card, local: true, url: pay_signups_path, method: 'POST', class: 'l-single-inner registration-form', id: "card__form", html: {name: "inputForm"} , novalidate: 'novalidate' do |f|
          .l-single-content
            .form-group
              = f.label :card_number, "カード番号"
              %sapn.form-require
                必須
              - if @card.errors.full_messages_for(:card_number).any?
                = f.number_field :number, placeholder: "半角数字のみ", class: 'input-default--has-error'
              - else
                = f.number_field :number, placeholder: "半角数字のみ", class: 'input-default'
              = render partial: 'error-messages', locals: { user: @card, column: "card_number"}
              %ul#card-no-error-wrapper.has-error-text
              %ul.signup-card-list
                %li
                  %img{src: "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?3466462615", width: "49", height: "20", alt: ""}
                %li
                  %img{src: "//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?3466462615", width: "34", height: "20", alt: ""}
                %li
                  %img{src: "//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?3466462615", width: "30", height: "20", alt: ""}
                %li
                  %img{src: "//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?3466462615", width: "32", height: "20", alt: ""}
                %li
                  %img{src: "//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?3466462615", width: "21", height: "20", alt: ""}
                %li
                  %img{src: "//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?3466462615", width: "32", height: "20", alt: ""}
                %li
                  %img{src: "//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?3466462615", width: "32", height: "20", alt: ""}
            .form-group.signup-form-expire
              = f.label :card_expiration_date, "有効期限"
              %sapn.form-require
                必須
              %br/
              .select-wrap.half
                -# = f.date_select(:card_expiration_date_month, discard_year: true, discard_day: true, use_month_numbers: true, use_two_digit_numbers: true, prompt: "--")
                - if @card.errors.full_messages_for(:card_expiration_date_month).any?
                  = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{}, id: "payment_card_expire_mm", class: "select-default--has-error"
                - else
                  = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{}, id: "payment_card_expire_mm", class: "select-default"
                = render partial: 'error-messages', locals: { user: @card, column: "card_expiration_date_month"}
                = fa_icon 'chevron-down'
                %span 月
              .select-wrap.half
                -# = f.date_select(:card_expiration_date_year, discard_month: true, discard_day: true, start_year: (Time.now.year), end_year: (Time.now.year+10), prompt: "--")
                - if @card.errors.full_messages_for(:card_expiration_date_year).any?
                  = f.select :exp_year,[["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2015],["26",2026],["27",2027],["28",2028],["29",2029]],{}, id: "payment_card_expire_yy", class: "select-default--has-error"
                - else
                  = f.select :exp_year,[["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2015],["26",2026],["27",2027],["28",2028],["29",2029]],{}, id: "payment_card_expire_yy", class: "select-default"
                = render partial: 'error-messages', locals: { user: @card, column: "card_expiration_date_year"}
                = fa_icon 'chevron-down'
                %span 年
              %ul#card-mm-error-wrapper.has-error-text
              %ul#card-yy-error-wrapper.has-error-text
            .form-group
              = f.label :card_security_code, "セキュリティコード"
              %sapn.form-require
                必須
              - if @card.errors.full_messages_for(:card_security_code).any?
                = f.number_field :cvc, placeholder: "カードの背面4桁もしくは3桁の番号", class: 'input-default--has-error', id: "card_cvc"
              - else
                = f.number_field :cvc, placeholder: "カードの背面4桁もしくは3桁の番号", class: 'input-default', id: "card_cvc"
              = render partial: 'error-messages', locals: { user: @card, column: "card_security_code"}
              %ul#security-code-error-wrapper.has-error-text
              .signup-seqcode
                %span.form-question?
                %label(for="label1")カード裏面の番号とは？
                %input#label1(type="checkbox" name="")
                .seqcode-show
                  カードの裏面をご参照ください。
                  %img{src: "//www-mercari-jp.akamaized.net/assets/img/signup/seq-card.png?3466462615", width: "240", alt: ""}
            #card_token
            = f.submit '次へ進む', id: "token_submit", class: "btn-default btn-red"
    = render 'registration_footer'