config/routes.rb
Rails.application.routes.draw do
  #クレジットカード登録
  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
    end
  end

  devise_for :users
  root "items#index"
  get "items/item"
  resources :signups, only: [:create] do
    collection do
      get "registration"
      get "newmember"
      get "phonenumber"
      get "authentication"
      get "address"
      get "payment"
      get "completion"
      post 'pay'
    end
  end

  resources :items,only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    # get "items/item"
    get "items/bought"
    get "items/purchase"
  
    get "items/search"
    get "items/buy"
    get "items/transaction"
    
    member do
      get 'select'
    end
    collection do
      get 'search'
    end
    resources :purchases, only: [:index, :show] do
      member do
      end
      collection do
        post 'pay', to: 'purchases#pay'
        get 'buy', to: 'purchases#buy'
      end
    end
  end
      
  resources :categories, only: [:show, :index]

  resources :users, only: [:show] do
    member do

    end
    collection do 
      get 'card_add_btn'
      get 'card_delete_btn'
      get 'card_input_info'
      get 'create'
      get 'information'
      get 'logout'
      get 'mypage'
      get 'profile'  
      get 'seller_selling'
      get 'seller_trading'
      get 'seller_sold'
    end
  end

  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
        

        has_many :items
        has_many :cards
  
  # mount_uploader :image, ImageUploader

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PHONE_REGEX = /\A\d{10,11}\z/
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)[a-zA-Z\d]{7,128}+\z/
  VALID_POSTAL_CODE = /\A\d{3}-\d{4}\z/i
  VALID_CARD_NUMBER_REGEX = /\A\d{14,16}\z/
  VALID_SECURITY_CODE = /\A\d{3,4}\z/
  VALID_NAME_KANA = /\A[\p{katakana}\p{blank}ー－]+\z/
  
  #newmember
  validates :nickname, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX, message: 'のフォーマットが不適切です'}, allow_blank: true #エラーメッセージの重複を避ける
  validates :password, presence: true, length: {minimum: 7, maximum: 128}, format: { with: VALID_PASSWORD_REGEX, message: 'は英字(大・小文字)と数字両方を含むパスワードを設定してください'}, allow_blank: true
  validates :password_confirmation, length: {minimum: 7, maximum: 128}, format: { with: VALID_PASSWORD_REGEX, message: 'は英字(大・小文字)と数字両方を含むパスワードを設定してください'}, allow_blank: true
  validates :password_confirmation, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, format: { with: VALID_NAME_KANA, message: 'はカタカナで入力してください'}, allow_blank: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, format: { with: VALID_NAME_KANA, message: 'はカタカナで入力してください'}, allow_blank: true
  validates :first_name_kana, presence: true
  validates :birthdate_year, presence: true
  validates :birthdate_month, presence: true
  validates :birthdate_day, presence: true

  #phonenumber
  validates :phone_number, format: { with: VALID_PHONE_REGEX, message: 'の入力が正しくありません'}, allow_blank: true
  validates :phone_number, presence: true
  #authentication
  validates :authentication_code, numericality: { only_integer: true }, allow_blank: true
  validates :authentication_code, presence: true
  #address
  validates :address_last_name, presence: true
  validates :address_first_name, presence: true
  validates :address_last_name_kana, format: { with: VALID_NAME_KANA, message: 'はカタカナで入力してください'}, allow_blank: true
  validates :address_last_name_kana, presence: true
  validates :address_first_name_kana, format: { with: VALID_NAME_KANA, message: 'はカタカナで入力してください'}, allow_blank: true
  validates :address_first_name_kana, presence: true
  validates :postal_code, length: { maximum: 8 }, format: { with: VALID_POSTAL_CODE, message: 'のフォーマットが不適切です'}, allow_blank: true
  validates :postal_code, presence: true
  validates :prefecture, presence: true
  validates :city, presence: true
  validates :block_number, presence: true

  has_many :buyed_items, foreign_key: "buyer_id", class_name: "Item"
  has_many :selling_items, -> { where("buyer_id is NULL") }, foreign_key: "seller_id", class_name: "Item"
  has_many :trading_items, -> { where("buyer_id is not NULL") }, foreign_key: "seller_id", class_name: "Item"

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  private
  def callback_for(provider)
    @user = User.find_oauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #after_sign_in_path_forと同じパス
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to newmember_signups_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
  end

  def create
    @user = User.new
  end

  def information
  end

  def logout
  end

  def mypage
    @user = User.find_by(id:current_user.id)
    @items = Item.where(seller_id: @user.id)
   
  end

  def profile
  end

  def seller_selling
    @item_selling = User.find_by(id:current_user.id).selling_items
  end

  def seller_trading
    @item_trading = User.find_by(id:current_user.id).trading_items
  end

  def seller_sold
    # @item_trading = User.find_by(id:current_user.id).sold_items
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_create-footer.html.haml
%footer.single-footer
  %ul.single-footer__clearfix
    %li.single-footer__clearfix__lists
      =link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
    %li.single-footer__clearfix__lists
      =link_to "メルカリ利用規約", "https://www.mercari.com/jp/tos/"
    %li.single-footer__clearfix__lists
      =link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"
  .single-footer__logo
    = link_to "", href: "https://www.mercari.com/jp/"
    %img.single-footer__logo__image{alt: "mercari", height: "65", src: "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?2296184308", width: "80"}
  %p
    %small
      &copy 2019 Mercari

app/views/users/_create-header.html.haml
.single-container	
  %header.single-header
    %h1
      =link_to "https://www.mercari.com/jp/" do
        %img(src="//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?2296184308" alt="mercari")

app/views/users/_slide_bar.html.haml
.container__side
  .container__side--nav
    %ul.container__side--nav-listing
      %li.container__side--nav-listing-list
        =link_to "マイページ", mypage_users_path,class:"container__side--nav-listing-list-item"
          
      %li.container__side--nav-listing-list
        =link_to "お知らせ", "",class:"container__side--nav-listing-list-item"
          
      %li.container__side--nav-listing-list
        =link_to "やることリスト", "",class:"container__side--nav-listing-list-item"
          
      %li.container__side--nav-listing-list
        =link_to "いいね！一覧", "",class:"container__side--nav-listing-list-item"
          
      %li.container__side--nav-listing-list
        =link_to "出品する", new_item_path, class:"container__side--nav-listing-list-item"
  
      %li.container__side--nav-listing-list
        =link_to "出品した商品 - 出品中", seller_selling_users_path,class:"container__side--nav-listing-list-item"
        
      %li.container__side--nav-listing-list
        =link_to "出品した商品 - 取引中", seller_trading_users_path,class:"container__side--nav-listing-list-item"
        
      %li.container__side--nav-listing-list
        =link_to "出品した商品 - 売却済み", seller_sold_users_path,class:"container__side--nav-listing-list-item"
      
      %li.container__side--nav-listing-list
        =link_to "購入した商品 - 取引中", "",class:"container__side--nav-listing-list-item"
        
      %li.container__side--nav-listing-list
        =link_to "購入した商品 - 過去の取引", "",class:"container__side--nav-listing-list-item"
        
      %li.container__side--nav-listing-list
        =link_to "ニュース一覧", "",class:"container__side--nav-listing-list-item"
  
      %li.container__side--nav-listing-list
        =link_to "評価一覧", "",class:"container__side--nav-listing-list-item"
        
      %li.container__side--nav-listing-list
        =link_to "ガイド", "",class:"container__side--nav-listing-list-item"
        
      %li.container__side--nav-listing-list
        =link_to "お問い合わせ", "",class:"container__side--nav-listing-list-item"
  
    %h3.container__side--nav-merupay  メルペイ
    %ul.container__side--nav-listing
      %li.container__side--nav-listing-list
        =link_to "残高・振込申請", "",class:"container__side--nav-listing-list-item"
        
      %li.container__side--nav-listing-list
        =link_to "ポイント", "",class:"container__side--nav-listing-list-item"

    %h3.container__side--nav-setting  設定
    %ul.container__side--nav-listing
      %li.container__side--nav-listing-list
        =link_to "プロフィール", profile_users_path,class:"container__side--nav-listing-list-item"
        
      %li.container__side--nav-listing-list
        =link_to "発送元・お届け先住所変更", "",class:"container__side--nav-listing-list-item"
        
      %li.container__side--nav-listing-list
        =link_to "支払い方法", cards_path,class:"container__side--nav-listing-list-item"
        
      %li.container__side--nav-listing-list
        =link_to "メール/パスワード", "",class:"container__side--nav-listing-list-item"
        
      %li.container__side--nav-listing-list
        =link_to "本人情報", information_users_path,class:"container__side--nav-listing-list-item"
  
      %li.container__side--nav-listing-list
        =link_to "電話番号の確認", "",class:"container__side--nav-listing-list-item"
        
      %li.container__side--nav-listing-list
        =link_to "ログアウト", logout_users_path,class:"container__side--nav-listing-list-item"

app/views/users/card_add_btn.html.haml
=render "items/header"
.signups-body
  - breadcrumb :payment
  =render 'categories/bread'
%main.container
  .container__content
    %section.container__content--box 
      %h2.container__content--box-head 支払い方法
      .container__content--box-inner
        %section.container__content--box-inner-section
          .container__content--box-inner-section-sub
            %h3.container__content--box-inner-section-sub-head クレジットカード一覧
        %section.container__content--box-inner-add
          .container__content--box-inner-add-card
            =link_to "",class:"container__content--box-inner-add-card-btn" do
              %i.icon-container__content--box-inner-add-card-btn
                クレジットカードを追加する
        .container__content--box-inner-help
          =link_to "",class:"container__content--box-inner-help-link" do
            %span 支払い方法について
            %i.icon-container__content--box-inner-help-link
   
  =render 'slide_bar'

=render "items/footer"

app/views/users/card_delete_btn.html.haml
=render "items/header"
.signups-body
  - breadcrumb :payment
  =render 'categories/bread'

%main.container
  .container__content
    %section.container__content--box 
      %h2.container__content--box-head 支払い方法
      .container__content--box-inner
        %section.container__content--box-inner-center
          .container__content--box-inner-center-head
            %h3.container__content--box-inner-center-head-title クレジットカード一覧
          %ul.container__content--box-inner-center-body
            %li.container__content--box-inner-center-body-list
              %form(action ="" class="container__content--box-inner-center-body-list-type" id="" data-adyen-id ="" method ="POST")
                %figure
                  = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?3466462615', class:'container__content--box-inner-center-body-list-type-card-image', width:'49', height:'15'
                %input(type="hidden" name="__csrf_value" value="54d4a567188d7fe06b574db6f8f81d3e8984a5a7dbbeb44e0a20c2583e070ee32876445b6afe0b9a3c0c2e14fb9b3b161f6471c968dace7f3013335eece7a8d72")
                %input(type="hidden" name="card_sequence_no" value="KBrfRrCb4SwqXiW6YunmKqcc")
                .container__content--box-inner-center-body-list-type-num ************0713
                .container__content--box-inner-center-body-list-type-mum 04 / 23
                %input(type="hidden" name="method" value="card")
                =link_to "http://localhost:3000/users/card_input_info", class: "container__content--box-inner-center-body-list-type-btn" do
                  削除する

        .container__content--box-inner-help
          =link_to "",class:"container__content--box-inner-help-link" do
            %span 支払い方法について
            %i.icon-container__content--box-inner-help-link

  =render 'slide_bar'

= render "items/footer"

=render 'items/selling_btn'

app/views/users/information.html.haml
= render "items/header"
.signups-body
  - breadcrumb :identification
  =render 'categories/bread'
%main.container
  .container__content
    %section.container__content--box 
      %h2.container__content--box-head 本人情報の登録
      %form(action ="https://www.mercari.com/jp/mypage/identification/save" class="container__content--box-inner" data-adyen-id ="card-form" method ="POST" novalidate ="novalidate")
        .container__content--box-inner-explanation
          %p.container__content--box-inner-explanation-text
            お客さまの本人情報をご登録ください。
            %br 
              登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
          %p.container__content--box-inner-explanation-link
            =link_to "",class:"container__content--box-inner-explanation-link-text" do
              %span 本人確認書類のアップロードについて
              %i.icon-container__content--box-inner-explanation-link-text-btn
        .container__content--box-inner-group
          %label お名前
          %p 山田 太郎
        .container__content--box-inner-group
          %label お名前カナ
          %p ヤマダ タロウ
        .container__content--box-inner-group
          %label(for="birthday") 生年月日
          %p 1999/09/09
        .container__content--box-inner-group
          %label(for="zip-code") 郵便番号
          %span.form-arbitrary 任意
          %input(type="text" value="8201111" name="zip-code" placeholder="例)1234567" class="input-default")
        .container__content--box-inner-group
          %label(for="prefecture") 都道府県
          %span.form-arbitrary 任意
          .container__content--box-inner-group-select
            %i.icon-arrow-bottom
            %select.select-default(name="prefecture")
              %option(value="")--
              %option(value="北海道")北海道
              %option(value="青森県")青森県
              %option(value="岩手県")岩手県
              %option(value="宮城県")宮城県
              %option(value="秋田県")秋田県
              %option(value="山形県")山形県
              %option(value="福島県")福島県
              %option(value="茨城県")茨城県
              %option(value="栃木県")栃木県
              %option(value="群馬県")群馬県
              %option(value="埼玉県")埼玉県
              %option(value="千葉県")千葉県
              %option(value="東京都")東京都
              %option(value="神奈川県")神奈川県
              %option(value="新潟県")新潟県
              %option(value="富山県")富山県
              %option(value="石川県")石川県
              %option(value="福井県")福井県
              %option(value="山梨県")山梨県
              %option(value="長野県")長野県
              %option(value="岐阜県")岐阜県
              %option(value="静岡県")静岡県
              %option(value="愛知県")愛知県
              %option(value="三重県")三重県
              %option(value="滋賀県")滋賀県
              %option(value="京都府")京都府
              %option(value="大阪府")大阪府
              %option(value="兵庫県")兵庫県
              %option(value="奈良県")奈良県
              %option(value="和歌山県")和歌山県
              %option(value="鳥取県")鳥取県
              %option(value="島根県")島根県
              %option(value="岡山県")岡山県
              %option(value="広島県")広島県
              %option(value="山口県")山口県
              %option(value="徳島県")徳島県
              %option(value="香川県")香川県
              %option(value="愛媛県")愛媛県
              %option(value="高知県")高知県
              %option(value="福岡県")福岡県
              %option(value="佐賀県")佐賀県
              %option(value="長崎県")長崎県
              %option(value="熊本県")熊本県
              %option(value="大分県")大分県
              %option(value="宮崎県")宮崎県
              %option(value="鹿児島県")鹿児島県
              %option(value="沖縄県")沖縄県
              
        .container__content--box-inner-group  
          %label(for="city") 市区町村
          %span.form-arbitrary 任意
          %input(type="text" value="" name="city" placeholder="例) 横浜市緑区" class="input-default")
        .container__content--box-inner-group
          %label(for="address1_label") 番地
          %span.form-arbitrary 任意
          %input(type="text" value="" name="address1" placeholder="例) 青山1-1-1" class="input-default")
        .container__content--box-inner-group
          %label(for="address2_label") 建物名
          %span.form-arbitrary 任意
          %input(type="text" value="" name="address2" placeholder="例) 柳ビル103" class="input-default")
        %button(type="submit" class="btn-default btn-red") 登録する

        .container__content--box-inner-group
          %p
            =link_to "",class:"container__content--box-inner-help-link" do
              %span 本人情報の登録について
              %i.icon-container__content--box-inner-help-link

  =render 'slide_bar'

= render "items/footer"

=render 'items/selling_btn'

app/views/users/logout.html.haml
= render "items/header"
.signups-body
  - breadcrumb :logout
  =render 'categories/bread'

%main.container
  .container__content
    .container__content--box
      %form(action="" method="post" class="container__content--box-form")
        .container__content--box-form-content
          = link_to destroy_user_session_path, method: 'DELETE', class: "container__content--box-form-content-btn" do
            ログアウト

  =render 'slide_bar'

= render "items/footer"

=render 'items/selling_btn'

app/views/users/seller_selling.html.haml
= render "items/header"
.signups-body
  - breadcrumb :exhibiting
  =render 'categories/bread'

%main.container
  .container__content
    %section.container__content--group
      %h2.container__content--group-head-selling 出品した商品
      %ul.container__content--group-tabs
        %li.container__content--group-tabs-list-active
          %h3
            =link_to "出品中",seller_selling_users_path,class:"container__content--group-tabs-list-active-name"
        %li.container__content--group-tabs-list
          %h3
            =link_to "取引中",seller_trading_users_path,class:"container__content--group-tabs-list-name"
        %li.container__content--group-tabs-list
          %h3
            =link_to "売却済",seller_sold_users_path,class:"container__content--group-tabs-list-name"
      .container__content--group-wrap
        %ul.container__content--group-wrap-listing
          -if @item_selling.blank?
            .container__content--group-wrap-listing-lists
              .container__content--group-wrap-listing-lists-list
                取引中の商品がありません
          -else
            - @item_selling.each do |item|
              %li 
                =link_to select_item_path(item),class:"container__content--group-wrap-listing-item" do
                  %figure
                    = image_tag "#{item.images.first.image}", class:'container__content--group-wrap-listing-item-image'
                  .container__content--group-wrap-listing-item-info
                    .container__content--group-wrap-listing-item-info-text
                      = "「#{item.title}」"
                    .container__content--group-wrap-listing-item-info-box
                      %span.container__content--group-wrap-listing-item-info-box-count
                        %i.icon-like
                        %span 0
                      %span.container__content--group-wrap-listing-item-info-box-count
                        %i.icon-message
                        %span 0
                      .container__content--group-wrap-listing-item-info-box-text-status
                        出品中
                  %i.icon-arrow-right

    %ul.container__content--pager
      %li.container__content--pager-prev 
        =link_to "",class:"container__content--pager-prev-link " do
          %i.icon-arrow-left 
      %li.container__content--pager-next
        =link_to "",class:"container__content--pager-next-link" do
          %i.icon-arrow-right

  =render 'slide_bar'

= render "items/footer"

=render 'items/selling_btn'

app/views/users/seller_sold.html.haml
= render "items/header"
.signups-body
  - breadcrumb :sold
  =render 'categories/bread'

%main.container
  .container__content
    %section.container__content--group
      %h2.container__content--group-head-selling 出品した商品
      %ul.container__content--group-tabs
        %li.container__content--group-tabs-list
          %h3
            =link_to "出品中",seller_selling_users_path,class:"container__content--group-tabs-list-name"
        %li.container__content--group-tabs-list
          %h3
            =link_to "取引中",seller_trading_users_path,class:"container__content--group-tabs-list-name"
        %li.container__content--group-tabs-list-active
          %h3
            =link_to "売却済",seller_sold_users_path,class:"container__content--group-tabs-list-active-name"
      .container__content--group-wrap
        %ul.container__content--group-wrap-listing
          -if @item_trading.blank?
            .container__content--group-wrap-listing-lists
              .container__content--group-wrap-listing-lists-list
                取引中の商品がありません
          -else
            - @item_trading.each do |item|
              %li 
                =link_to "",class:"container__content--group-wrap-listing-item" do
                  %figure
                    = image_tag "#{item.images.first.image}", class:'container__content--group-wrap-listing-item-image'
                  .container__content--group-wrap-listing-item-info
                    .container__content--group-wrap-listing-item-info-text 
                      = "#{item.title}"
                    .container__content--group-wrap-listing-item-info-box-gray
                      売却済
                  %i.icon-arrow-right

    %ul.container__content--pager
      %li.container__content--pager-prev 
        =link_to "",class:"container__content--pager-prev-link " do
          %i.icon-arrow-left 
      %li.container__content--pager-next
        =link_to "",class:"container__content--pager-next-link" do
          %i.icon-arrow-right

  =render 'slide_bar'

= render "items/footer"

=render 'items/selling_btn'

app/views/users/seller_trading.html.haml
= render "items/header"
.signups-body
  - breadcrumb :trading
  =render 'categories/bread'

%main.container
  .container__content
    %section.container__content--group
      %h2.container__content--group-head-selling 出品した商品
      %ul.container__content--group-tabs
        %li.container__content--group-tabs-list
          %h3
            =link_to "出品中",seller_selling_users_path,class:"container__content--group-tabs-list-name"
        %li.container__content--group-tabs-list-active
          %h3
            =link_to "取引中",seller_trading_users_path,class:"container__content--group-tabs-list-active-name"
        %li.container__content--group-tabs-list
          %h3
            =link_to "売却済",seller_sold_users_path,class:"container__content--group-tabs-list-name"
      .container__content--group-wrap
        %ul.container__content--group-wrap-listing
          -if @item_trading.blank?
            .container__content--group-wrap-listing-lists
              .container__content--group-wrap-listing-lists-list
                取引中の商品がありません
          -else
            - @item_trading.each do |item|
              %li 
                =link_to "",class:"container__content--group-wrap-listing-item" do
                  %figure
                    = image_tag "#{item.images.first.image}", class:'container__content--group-wrap-listing-item-image'
                  .container__content--group-wrap-listing-item-info
                    .container__content--group-wrap-listing-item-info-text 
                      = "#{item.title}"
                    .container__content--group-wrap-listing-item-info-box-red
                      発送待ち
                  %i.icon-arrow-right

    %ul.container__content--pager
      %li.container__content--pager-prev 
        =link_to "",class:"container__content--pager-prev-link " do
          %i.icon-arrow-left 
      %li.container__content--pager-next
        =link_to "",class:"container__content--pager-next-link" do
          %i.icon-arrow-right

  =render 'slide_bar'

= render "items/footer"

=render 'items/selling_btn'