config/routes.rb
Rails.application.routes.draw do
  #クレジットカード登録
  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
    end
  end

  devise_for :users
  root "items#index"
  get "items/item"
  resources :signups, only: [:create] do
    collection do
      get "registration"
      get "newmember"
      get "phonenumber"
      get "authentication"
      get "address"
      get "payment"
      get "completion"
      post 'pay'
    end
  end

  resources :items,only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    # get "items/item"
    get "items/bought"
    get "items/purchase"
  
    get "items/search"
    get "items/buy"
    get "items/transaction"
    
    member do
      get 'select'
    end
    collection do
      get 'search'
    end
    resources :purchases, only: [:index, :show] do
      member do
      end
      collection do
        post 'pay', to: 'purchases#pay'
        get 'buy', to: 'purchases#buy'
      end
    end
  end
      
  resources :categories, only: [:show, :index]

  resources :users, only: [:show] do
    member do

    end
    collection do 
      get 'card_add_btn'
      get 'card_delete_btn'
      get 'card_input_info'
      get 'create'
      get 'information'
      get 'logout'
      get 'mypage'
      get 'profile'  
      get 'seller_selling'
      get 'seller_trading'
      get 'seller_sold'
    end
  end

  

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :user, foreign_key: 'user_id'
  belongs_to :category
  belongs_to :brand
  belongs_to :condition
  belongs_to :delivery_area
  belongs_to :delivery_day
  belongs_to :delivery_fee
  belongs_to :delivery_method
  belongs_to :size
  has_many :images, dependent: :destroy
  
  accepts_nested_attributes_for :images, allow_destroy: true

  def previous
    user.items.order('created_at desc, id desc').where('created_at <= ? and id < ?', created_at, id).first
  end

  def next
    user.items.order('created_at desc, id desc').where('created_at >= ? and id > ?', created_at, id).reverse.first
  end


  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User", optional: true
end

app/controllers/item_controller.rb
class ItemsController < ApplicationController
  
  def index
    
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @items = Item.all

    @ladys_category = Category.find(1)
    @mens_category = Category.find(2)
    @elecs_category = Category.find(8)
    @hobys_category = Category.find(6)

    # @category = Category.find(params[:id])
    # Post.where(category_id: @category.subtree_ids)

    @ladys = Item.where(category_id:@ladys_category.subtree_ids).limit(10).order("created_at DESC")
    @mens = Item.where(category_id:@mens_category.subtree_ids).limit(10).order("created_at DESC")
    @elecs = Item.where(category_id:@elecs_category.subtree_ids).limit(10).order("created_at DESC")
    @hobys = Item.where(category_id:@hobys_category.subtree_ids).limit(10).order("created_at DESC")
    @chanels = Item.where(brand_id:1).order('id DESC').limit(10)
    @vuittons = Item.where(brand_id:3).order('id DESC').limit(10)
    @supremes = Item.where(brand_id:4).order('id DESC').limit(10)
    @nikes = Item.where(brand_id:2).order('id DESC').limit(10)
  end

  def search
    if params[:l_cat]
      @m_cat = Category.find(params[:l_cat]).children
    elsif params[:m_cat]
      @s_cat = Category.find(params[:m_cat]).children
    elsif params[:size]
      @size = Size.where(params[:size])
    else 
      @deliver = DeliveryMethod.where(params[:deliver])
    end
    respond_to do |format|
      format.html
      format.json 
    end
  end

  def show
    @item = Item.find(params[:id])
    @users = @item.user.items.order("created_at DESC").limit(6)
    @brands = @item.brand.items.order("created_at DESC").limit(6)
  end

  def new
    @item = Item.new
    @item.images.build
    # gon.item = @item
    # gon.images = @item.images

    # # @item.item_imagse.image_urlをバイナリーデータにしてビューで表示できるようにする
    # require 'base64'
    # require 'aws-sdk'

    # gon.images_binary_datas = []
    # if Rails.env.production?
    #   client = Aws::S3::Client.new(
    #                          region: 'ap-northeast-1',
    #                          access_key_id: Rails.application.credentials.aws[:access_key_id],
    #                          secret_access_key: Rails.application.credentials.aws[:secret_access_key],
    #                          )
    #   @item.images.each do |image|
    #     binary_data = client.get_object(bucket: 'freemarket-sample-60a', key: image.image_url.file.path).body.read
    #     gon.images_binary_datas << Base64.strict_encode64(binary_data)
    #   end
    # else
    #   @item.images.each do |image|
    #     binary_data = File.read(image.image_url.file.file)
    #     gon.images_binary_datas << Base64.strict_encode64(binary_data)
    #   end
    # end
  end
  
  def create
    @item = Item.new(item_params)
    # binding.pry
    # インスタンスの保存に成功した場合の処理
     if @item.save!
      redirect_to root_path
    # インスタンスの保存に失敗した場合の処理
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.user_id == current_user.id
      @item.update(item_params)
      redirect_to item_path(@item)
    else
      redirect_to item_path(@item), notice: "商品の編集はできません"
    end
  end


  def purchase
  end

  def select
    @item = Item.find(params[:id])
  end

  def bought
  end 

  def destroy
    @item = Item.find(params[:id])
    @item.destroy 
    redirect_to controller: 'users',action: 'seller_selling'
  end

  # def update
  #   # ブランド名がstringでparamsに入ってくるので、id番号に書き換え
  #   if  brand = Brand.find_by(name: params[:item][:brand_id])
  #     params[:item][:brand_id] = brand.id
  #   else
  #     params[:item][:brand_id] = Brand.create(name: params[:item][:brand_id]).id
  #   end

  #   @item = Item.find(params[:id])

  #   # 登録済画像のidの配列を生成
  #   ids = @item.images.map{|image| image.id }
  #   # 登録済画像のうち、編集後もまだ残っている画像のidの配列を生成(文字列から数値に変換)
  #   exist_ids = registered_image_params[:ids].map(&:to_i)
  #   # 登録済画像が残っていない場合(配列に０が格納されている)、配列を空にする
  #   exist_ids.clear if exist_ids[0] == 0

  #   if (exist_ids.length != 0 || new_image_params[:images][0] != " ") && @item.update(item_params)

  #     # 登録済画像のうち削除ボタンをおした画像を削除
  #     unless ids.length == exist_ids.length
  #       # 削除する画像のidの配列を生成
  #       delete_ids = ids - exist_ids
  #       delete_ids.each do |id|
  #         @item.item_images.find(id).destroy
  #       end
  #     end

  #     # 新規登録画像があればcreate
  #     unless new_image_params[:images][0] == " "
  #       new_image_params[:images].each do |image|
  #         @item.images.create(image_url: image, item_id: @item.id)
  #       end
  #     end

  #     flash[:notice] = '編集が完了しました'
  #     redirect_to item_path(@item), data: {turbolinks: false}

  #   else
  #     flash[:alert] = '未入力項目があります'
  #     redirect_back(fallback_location: root_path)
  #   end

  # end


  private
  def item_params
    params.require(:item).permit(:title, :text, :category_id, :size_id, :brand_id, :condition_id, :delivery_fee_id, :delivery_method_id, :delivery_area_id, :delivery_day_id, :price, images_attributes: [:image, :id]).merge(seller_id: current_user.id, user_id: current_user.id)
  end

  def registered_image_params
    params.require(:registered_images_ids).permit({ids: []})
  end

  def new_image_params
    params.require(:new_images).permit({images: []})
  end

end

app/views/items/_comment.html.haml
.item__message
  .item__message__box
    .item__message__box__content
      %form.item-message
        %p<>
          相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      %textarea.text-area
      %button.message-submit
        %span コメントする
      -# %textarea{disabled:"disabled",class:"text-area disabled"}
      -# %button{disabled:"disabled",class:"message-submit disabled"}
        %span
          売り切れのためコメントできません  
    %aside.item-modal

app/views/items/_header.html.haml
.header-hyde.header-pop.hyde
  .header-hyde__top
    =link_to "/",class:"header-hyde__top__link" do
      =image_tag src="https://web-jp-assets.mercdn.net/_next/static/images/logo-acdd90ac4f472d5a6f7a330d33ab1225.svg",class:"header-hyde__top__link__image"
    - if user_signed_in?
      .header-hyde__top__mymenu
        .header-hyde__top__mymenu__list
          =link_to "",class:"header-hyde__top__mymenu__list__link" do
            =fa_icon "bell",class:"header-hyde__top__mymenu__list__link__bell" 
        .header-hyde__top__mymenu__list
          =link_to "",class:"header-hyde__top__mymenu__list__link" do
            =fa_icon "check",class:"header-hyde__top__mymenu__list__link__check"
        .header-hyde__top__mymenu__list
          =link_to "",class:"header-hyde__top__mymenu__list__link" do
            =image_tag src="https://static.mercdn.net/images/member_photo_noimage_thumb.png",class:"header-hyde__top__mymenu__list__link__image"
    - else
      .header-hyde__top__button
        =link_to "新規会員登録","",class:"hyde-entry"
        =link_to "ログイン","",class:"hyde-login"

    
  .header-hyde__middle
    %form.search-form-hyde
      %input.search-text-hyde{placeholder:"何をお探しですか？"}
      %button.search-button-hyde
        =fa_icon "search",class:"search-icon-hyde"
  .header-hyde__bottom
    =link_to "",class:"header-hyde__bottom__link" do
      =fa_icon "list-ul",class:"header-hyde__bottom__link__list"
      %span.link-text-hyde カテゴリーから探す
    =link_to "",class:"header-hyde__bottom__link" do
      =fa_icon "tag",class:"header-hyde__bottom__link__tag"
      %span.link-text-hyde ブランドから探す

.header
  .header__row
    .header__row__top
      .header__row__top__title
        =link_to "/" do
          =image_tag src="https://web-jp-assets.mercdn.net/_next/static/images/logo-acdd90ac4f472d5a6f7a330d33ab1225.svg",class:"titleimage"
      .header__row__top__search
        %form.search-form
          %input.search-text{placeholder:"何かお探しですか？"}
          %button.search-button
            =fa_icon "search",class:"search-icon"
    .header__row__bottom
      .header__row__bottom__left
        .header__row__bottom__left__list
          =link_to "",class:"postlist" do
            =fa_icon "list-ul",class:"list-icon"
            %span.listfont カテゴリーから探す
          .categorys.popup
            %ul.categorys__lists
              - @parents.each do |parent|
                %li.categorys__lists__list
                  =link_to "#{parent.name}",category_path(parent),class:"categorys__lists__list__link" 
                  %ul.categorys__lists2
                    - parent.children.each do |child|  
                      %li.categorys__lists2__list
                        =link_to "#{child.name}",category_path(child),class:"categorys__lists2__list__link" 
                        %ul.categorys__lists3
                          - child.children.first(10).each do |grandchild|
                            %li.categorys__lists3__list
                              =link_to "#{grandchild.name}",category_path(grandchild),class:"categorys__lists3__list__link"
              %li.categorys__lists__list
                =link_to "カテゴリー一覧",categories_path,class:"categorys__lists__list__link" 
            
        .header__row__bottom__left__list 
          =link_to "",class:"postlist" do
            =fa_icon "tag",class:"list-icon"
            %span.listfont ブランドから探す
          .categorys.popup    
            %ul.categorys__lists
              %li.categorys__lists__list
                =link_to "シャネル","",class:"categorys__lists__list__link" 
              %li.categorys__lists__list
                =link_to "ナイキ","",class:"categorys__lists__list__link" 
              %li.categorys__lists__list
                =link_to "ルイ ヴィトン","",class:"categorys__lists__list__link" 
              %li.categorys__lists__list
                =link_to "シュプリーム","",class:"categorys__lists__list__link" 
              %li.categorys__lists__list
                =link_to "アディダス","",class:"categorys__lists__list__link"  
              %li.categorys__lists__list
                =link_to "ブランド一覧",categories_path,class:"categorys__lists__list__link"
      - if user_signed_in?
        %ul.header-users
          %li.header-users__menu
            =link_to "",class:"header-users__menu__link" do
              =fa_icon "heart",class:"header-users__menu__link__icon"
              いいね！一覧
          %li.header-users__menu
            =link_to "",class:"header-users__menu__link" do
              =fa_icon "bell",class:"header-users__menu__link__icon"
              お知らせ
              %span.popcount
            .header-users__popmenu.popup
              %ul
                %li
                  =link_to "",class:"header-users__popmenu__link" do
                    %figure.header-users__popmenu__link__newstop
                      =image_tag src="https://static.mercdn.net/images/mercari_profile.png",class:"header-users__popmenu__link__newstop__image"
                    .header-users__popmenu__link__newsbox
                      .header-users__popmenu__link__newsbox__text
                        事務局から個別メッセージ「ログイン通知」
                      %time.header-users__popmenu__link__newsbox__time
                        =fa_icon "clock",class:"header-users__popmenu__link__newsbox__time__icon"
                        %span.header-users__popmenu__link__newsbox__newstime__text
                          23時前                      
                    =fa_icon "chevron-right",class:"header-users__popmenu__link__icon"           
          %li.header-users__menu
            =link_to "",class:"header-users__menu__link" do
              =fa_icon "check",class:"header-users__menu__link__icon"
              やることリスト
            .header-users__popmenu.popup
              .header-users__popmenu__not<>
                現在、やることリストはありません
          %li.header-users__menu
            =link_to "/users/mypage",class:"heder-users__menu__link" do
              =image_tag src="https://static.mercdn.net/images/member_photo_noimage_thumb.png",class:"myimage"
              マイページ
            .header-users__popmenu.popup
              .header-users__popmenu__mypage
                %figure.header-users__popmenu__mypage__top
                  .header-users__popmenu__mypage__top__icon
                    =image_tag src="https://files.slack.com/files-pri/TK2M4NQC8-FNQU7GWPL/ios__________.jpg",class:"header-users__popmenu__mypage__top__icon__image"
                  %figcaption.header-users__popmenu__mypage__top__name
                    = current_user.nickname
                .header-users__popmenu__mypage__count
                  =link_to "評価:0","",class:"header-users__popmenu__mypage__count__link"
                  =link_to "出品数:0","",class:"header-users__popmenu__mypage__count__link"
                %ul.header-users__popmenu__mypage__credit
                  %li.header-users__popmenu__mypage__credit__list
                    =link_to "",class:"header-users__popmenu__mypage__credit__list__link" do
                      .header-users__popmenu__mypage__credit__list__link__name
                        売上金
                      .header-users__popmenu__mypage__credit__list__link__price
                        ¥0
                        =fa_icon "chevron-right",class:"header-users__popmenu__mypage__credit__list__link__price__icon"                    
                  %li.header-users__popmenu__mypage__credit__list
                    =link_to "",class:"header-users__popmenu__mypage__credit__list__link" do
                      .header-users__popmenu__mypage__credit__list__link__name
                        ポイント
                      .header-users__popmenu__mypage__credit__list__link__price
                        P0                 
                        =fa_icon "chevron-right",class:"header-users__popmenu__mypage__credit__list__link__price__icon"
                .header-users__popmenu__mypage__status
                  %ul.header-users__popmenu__mypage__status__list
                    %li
                      =link_to "",class:"header-users__popmenu__mypage__status__list__link" do
                        いいね！一覧  
                        =fa_icon "chevron-right",class:"header-users__popmenu__mypage__status__list__link__icon"
                    %li
                      =link_to "",class:"header-users__popmenu__mypage__status__list__link" do
                        出品した商品 - 出品中  
                        =fa_icon "chevron-right",class:"header-users__popmenu__mypage__status__list__link__icon"
                    %li
                      =link_to "",class:"header-users__popmenu__mypage__status__list__link" do
                        出品した商品 - 取引中
                        =fa_icon "chevron-right",class:"header-users__popmenu__mypage__status__list__link__icon"
                    %li
                      =link_to "",class:"header-users__popmenu__mypage__status__list__link" do
                        出品した商品 - 売却済み 
                        =fa_icon "chevron-right",class:"header-users__popmenu__mypage__status__list__link__icon"
                    %li
                      =link_to "",class:"header-users__popmenu__mypage__status__list__link" do
                        購入した商品 - 取引中
                        =fa_icon "chevron-right",class:"header-users__popmenu__mypage__status__list__link__icon"
                    %li
                      =link_to "",class:"header-users__popmenu__mypage__status__list__link" do
                        購入した商品 - 過去の取引
                        =fa_icon "chevron-right",class:"header-users__popmenu__mypage__status__list__link__icon"
      - else
        .header__row__bottom__rigth
          .header__row__bottom__rigth__entry
            =link_to "新規会員登録", registration_signups_path,class:"entry-button" 
          .header__row__bottom__rigth__login
            =link_to "ログイン", new_user_session_path,class:"login-button"

app/views/items/_new-header.html.haml
.single-container	
  %header.single-header
    %h1
      =link_to root_path do
        %img(src="//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?2296184308" alt="mercari")

app/views/items/_pop-transact.html.haml
.transact
  %h3
    %i.far.fa-clock
    %span 発送をお待ちください
  %p 出品者からの発送通知をお待ちください

app/views/items/_selling_btn.html.haml
.form
  =link_to new_item_path,class:"postform" do
    .form__button
      .form__button__title 出品
      =fa_icon "camera",class:"form__button__icon fa-2x"

app/views/items/bought.html.haml
= render "new-header"
.main
  %h2.main__head
    商品は既に売り切れています
  .main__center
    = link_to "商品画面へ戻る", class: ".main__center__item-page"
= render "new-footer"

app/views/items/exhibit.html.haml
.modal
  %h5.modal__head
    出品が完了しました
  .modal__text
    %p
      あなたが出品した商品は「出品した商品一覧」からいつでも見ることができます。   
    = link_to "続けて出品する", class: "modal__text__continue"
    = link_to "商品ページへ行ってシェアする", class: "modal__text__items-page"

app/views/items/new.html.haml
= render "new-header"

= form_for(@item) do |f|
  .items-sell
    .items-sell__infomations
      %h2.items-sell__infomations__item
        商品の情報を入力
    
    .items-sell__imgs
      %h3.items-sell__imgs__head 
        出品画像
        %span.items-sell__imgs__head__required
          必須 
      %p 最大10枚までアップロードできます

      = f.fields_for :images do |image|
        = image.label :image ,class: "input_area" do
          .items-sell__imgs__dropzone
            = image.file_field :image, id: "item_images_attributes_0_image", class: "upload-image"
            #preview
              -# １〜５枚目プレビュー表示
              .items-sell__imgs__dropzone__input                           
                .items-sell__imgs__dropzone__input__description
                  .items-sell__imgs__dropzone__input__description__text
                    ドラッグアンドドロップ
                    %br
                    またはクリックしてファイルをアップロード

        -# .items-sell__imgs__dropzone2
        -#   #preview2
        -#     -# ６〜１０枚目プレビュー表示
        -#     .items-sell__imgs__dropzone2__input2
        -#       = image.label :image, for: "upload-image" do
        -#         .input_area
        -#           = image.file_field :image_url, id: "upload-image", class: "upload-image", 'data-image': 0
        -#           .btn_edit
        -#             編集
        -#           .btn_delete
        -#             削除
        -#         .items-sell__imgs__dropzone2__input2__description
        -#           .items-sell__imgs__dropzone2__input2__description__text
        -#             ドラッグアンドドロップ
        -#             %br
        -#             またはクリックしてファイルをアップロード
  
    -# %p.items-sell__imgs__no-imgs
    -#   画像がありません

    .items-sell__message
      .items-sell__message__name
        %label.items-sell__message__name__head
          商品名
          %span.items-sell__message__name__head__required
            必須
          = f.text_field :title, class: "items-sell__message__name__main2", placeholder: "商品名（必須40文字まで）"
        %p.items-sell__message__name__no-name
          -# 入力してください
      .items-sell__message__content
        %label.items-sell__message__content__head
          商品の説明
          %span.items-sell__message__content__head__required
            必須
          = f.text_area :text, class: "items-sell__message__content__main3", rows: 5, placeholder: "商品の説明（必須1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
        %p.items-sell__message__content__no-content
          -# 入力してください
          
    .items-sell__details.clearfix
      %label.items-sell__details__left
        商品の詳細
      .items-sell__details__right
        .items-sell__details__right__category
          %label.items-sell__details__right__category__head
            カテゴリー
            %span.items-sell__details__right__category__head__required
              必須
          .items-sell__details__right__category__frame
            %i
              = fa_icon 'angle-down', class: "fa-2x"
            = f.collection_select :category_id, @parents, :id, :name,{prompt: "---"}, class: "items-sell__details__right__category__frame__main", id: "parent-form", name: 'item[category_id]'
        .items-sell__details__right__status
          %label.items-sell__details__right__status__head
            商品の状態
            %span.items-sell__details__right__status__head__required
              必須
          .items-sell__details__right__status__frame
            %i
              = fa_icon 'angle-down', class: "fa-2x"
            = f.select :condition_id, [["新品、未使用","1"],["未使用に近い","2"],["目立った傷や汚れなし","3"],["やや傷や汚れあり","4"],["傷や汚れあり","5"],["全体的に状態が悪い","6"]], {prompt: "---"}, class: "items-sell__details__right__status__frame__main"
    .items-sell__delivery.clearfix
      .items-sell__delivery__left
        %label.items-sell__delivery__left__head
          配送について
          = link_to "？", "", class: "items-sell__delivery__left__inquiry"
      .items-sell__delivery__right
        .items-sell__delivery__right__burden
          %label.items-sell__delivery__right__burden__head
            配送料の負担
            %span.items-sell__delivery__right__burden__head__required
              必須
          .items-sell__delivery__right__burden__frame 
            %i
              = fa_icon 'angle-down', class: "fa-2x" 
            = f.select :delivery_fee_id, [["送料込み(出品者負担)","1"],["着払い(購入者負担)","2"]], {prompt: "---"}, class: "items-sell__delivery__right__burden__frame__main", id: "deliver-form", name: 'item[delivery_fee_id]'
        .items-sell__delivery__right__area
          %label.items-sell__delivery__right__area__head
            発送元の地域
            %span.items-sell__delivery__right__area__head__required
              必須
        .items-sell__delivery__right__area__frame
          .items-sell__delivery__right__area__frame__icon
            %i
              = fa_icon 'angle-down', class: "fa-2x"
            = f.select :delivery_area_id, [["北海道","1"],["青森県","2"],["秋田県","3"],["岩手県","4"],["宮城県","5"],["山形県","6"],["福島県","7"],["茨城県","8"],["栃木県","9"],["群馬県","10"],["埼玉県","11"],["千葉県","12"],["東京都","13"],["神奈川県","14"],["新潟県","15"],["富山県","16"],["石川県","17"],["福井県","18"],["山梨県","19"],["長野県","20"],["岐阜県","21"],["静岡県","22"],["愛知県","23"],["三重県","24"],["滋賀県","25"],["京都府","26"],["大阪府","27"],["兵庫県","28"],["奈良県","29"],["和歌山県","30"],["鳥取県","31"],["島根県","32"],["岡山県","33"],["広島県","34"],["山口県","35"],["徳島県","36"],["香川県","37"],["愛媛県","38"],["高知県","39"],["福岡県","40"],["佐賀県","41"],["長崎県","42"],["熊本県","43"],["大分県","44"],["宮崎県","45"],["鹿児島県","46"],["沖縄県","47"],["未定","48"]], { prompt: " ---"}, class: "items-sell__delivery__right__area__frame__main"
        .items-sell__delivery__right__date
          %label.items-sell__delivery__right__date__head
            発送までの日数
            %span.items-sell__delivery__right__date__head__required
              必須
        .items-sell__delivery__right__date__frame
          %i
            = fa_icon 'angle-down', class: "fa-2x"
          = f.select :delivery_day_id, [["1〜2日で発送","1"],["2〜3日で発送","2"],["4〜7日で発送","3"]], {prompt: "---"}, class: "items-sell__delivery__right__date__frame__main"
    .items-sell__price
      %label
        販売価格(300~9,999,999)
        = link_to "？", "", class: "items-sell__price__inquiry"
      %ul.items-sell__price__right
        %li.items-sell__price__right__list1
          %label.items-sell__price__right__list1__top
            価格
            %span.items-sell__price__right__list1__top__required
              必須
          .items-sell__price__right__list1__plices
            %p.items-sell__price__right__list1__plices__yen
            ¥
            = f.text_field :price, class: "items-sell__price__right__list1__plices__example", placeholder: "例）300"
            
        %li.items-sell__price__right__list2
          .items-sell__price__right__list2__center
            販売手数料(10%)
          .items-sell__price__right__list2__last
            ー
        %li.items-sell__price__right__list3
          .items-sell__price__right__list3__bottom
            販売利益
          .items-sell__price__right__list3__last
            ー
    .items-sell__exhibit        
      %p.items-sell__exhibit__1
        = link_to "禁止されている出品","", class: "items-sell__exhibit__1__ban"  
        、
        = link_to "行為","", class: "items-sell__exhibit__1__action"
        を必ずご確認ください。
      %p.items-sell__exhibit__2
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        = link_to " 偽ブランドの販売","", class: "items-sell__exhibit__2__fake"      
        は犯罪であり処罰される可能性があります。
      %p.items-sell__exhibit__3
        また、出品をもちまして
        = link_to "加盟店規約","", class: "items-sell__exhibit__3__terms"
        に同意したことになります。
      %button.items-sell__exhibit__decide
        = f.submit "出品する", class: "items-sell__exhibit__decide__window"
      %button.items-sell__exhibit__return 
        = link_to "もどる",  mypage_users_path
// 出品をおした時のモーダル発火
.modalOverlay.is-hite
  .modalOverlay__modal
    %h5.modalOverlay__modal__head
      出品が完了しました
    .modalOverlay__modal__text
      %p
        あなたが出品した商品は「出品した商品一覧」からいつでも見ることができます。   
      = link_to "続けて出品する", new_item_path, class: "modalOverlay__modal__text__continue"
      = link_to "商品ページへ行ってシェアする","", class: "modalOverlay__modal__text__items-page"
= render "new-footer"