config/routes.rb
Rails.application.routes.draw do
  #クレジットカード登録
  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
    end
  end

  devise_for :users
  root "items#index"
  get "items/item"
  resources :signups, only: [:create] do
    collection do
      get "registration"
      get "newmember"
      get "phonenumber"
      get "authentication"
      get "address"
      get "payment"
      get "completion"
      post 'pay'
    end
  end

  resources :items,only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    # get "items/item"
    get "items/bought"
    get "items/purchase"
  
    get "items/search"
    get "items/buy"
    get "items/transaction"
    
    member do
      get 'select'
    end
    collection do
      get 'search'
    end
    resources :purchases, only: [:index, :show] do
      member do
      end
      collection do
        post 'pay', to: 'purchases#pay'
        get 'buy', to: 'purchases#buy'
      end
    end
  end
      
  resources :categories, only: [:show, :index]

  resources :users, only: [:show] do
    member do

    end
    collection do 
      get 'card_add_btn'
      get 'card_delete_btn'
      get 'card_input_info'
      get 'create'
      get 'information'
      get 'logout'
      get 'mypage'
      get 'profile'  
      get 'seller_selling'
      get 'seller_trading'
      get 'seller_sold'
    end
  end

  

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # VALID_PHONE_REGEX = /\A\d{10,11}\z/
  # VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)[a-zA-Z\d]{7,128}+\z/
  # VALID_POSTAL_CODE = /\A\d{3}-\d{4}\z/i
  # VALID_CARD_NUMBER_REGEX = /\A\d{14,16}\z/
  # VALID_SECURITY_CODE = /\A\d{3,4}\z/
  # VALID_NAME_KANA = /\A[\p{katakana}\p{blank}ー－]+\z/

  # payment
  # validates :number, format: { with: VALID_CARD_NUMBER_REGEX, message: 'のフォーマットが不適切です'}, allow_blank: true
  # validates :number, presence: true
  # validates :exp_year, presence: true
  # validates :exp_month, presence: true
  # validates :cvc, length: {minimum: 3, maximum: 4}, format: { with: VALID_SECURITY_CODE, message: 'の入力が正しくありません'}, allow_blank: true
  # validates :cvc, presence: true
  ############## ↑上文はバリデーション検討中のためコメントアウト ##################
  
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # before_action :authenticate_user!
  require 'payjp'

  # クレジットカード情報入力画面
  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  # 登録画面で入力した情報をDBに保存
  def pay
    Payjp.api_key = "sk_test_9629ac740599209dbad72f1b"
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create( # ここで先ほど生成したトークンを顧客情報と紐付け、PAY.JP管理サイトに送信
        card: params['payjp-token'],
        metadata: {user_id: current_user.id} # 記述しなくても大丈夫です
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
        flash[:alert] = 'クレジットカード登録に失敗しました'
      end
    end
  end

  # 後ほど削除機能を実装します。
  def destroy #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = 'sk_test_9629ac740599209dbad72f1b'
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
  end

 # 後ほど登録したクレジットの表示画面を作成します。
  def show
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = "sk_test_9629ac740599209dbad72f1b"
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/delete.html.haml
=render "items/header"
.signups-body
  - breadcrumb :payment
  =render 'categories/bread'
%main.container
  .container__content
    %section.container__content--box 
      %h2.container__content--box-head 支払い方法
      .container__content--box-inner
        %section.container__content--box-inner-section
          .container__content--box-inner-section-sub
            %h3.container__content--box-inner-section-sub-head クレジットカード一覧
        %section.container__content--box-inner-add
          .container__content--box-inner-add-card
            =link_to "",class:"container__content--box-inner-add-card-btn" do
              %i.icon-container__content--box-inner-add-card-btn
                クレジットカードを追加する
        .container__content--box-inner-help
          =link_to "",class:"container__content--box-inner-help-link" do
            %span 支払い方法について
            %i.icon-container__content--box-inner-help-link
   
  =render 'slide_bar'

=render "items/footer"

app/views/cards/new.html.haml
= render "items/header"
.signups-body
  - breadcrumb :payment
  =render 'categories/bread'
%main.container
  .container__content
    %section.container__content--card
      %h2.container__content--card-title クレジットカード情報入力
      = form_with url: pay_cards_path, method: :post,class: "container__content--card-form",id: "card__form", html: {name: "inputForm"} do |f|
        .container__content--card-form-group
          .container__content--card-form-group-number
            %label(for ="payment_card_no") カード番号
            %span.container__content--card-form-group-number-require 必須
            = f.text_field :number, class: "container__content--card-form-group-number-input", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
            %ul#card-no-error-wrapper.container__content--card-form-group-number-error
              -# %li.container__content--card-form-group-number-error-text 必須項目です
            %ul.container__content--card-form-group-number-card
              %li.container__content--card-form-group-number-card-type
                =image_tag '//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?3466462615', width:'49', height:"20"
              %li.container__content--card-form-group-number-card-type
                =image_tag  "//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?3466462615", width:"34", height:"20" 
              %li.container__content--card-form-group-number-card-type
                =image_tag  "//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?3466462615", width:"30", height:"20" 
              %li.container__content--card-form-group-number-card-type
                =image_tag  "//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?3466462615", width:"32", height:"20"
              %li.container__content--card-form-group-number-card-type
                =image_tag  "//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?3466462615", width:"21", height:"20"
              %li.container__content--card-form-group-number-card-type
                =image_tag  "//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?3466462615", width:"32", height:"20"
              %li.container__content--card-form-group-number-card-type
                =image_tag  "//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?3466462615", width:"32", height:"20"
          .container__content--card-form-group-expiration
            %label(for = "payment_card_expire") 有効期限
            %span.container__content--card-form-group-expiration-require 必須
            %br/
            .container__content--card-form-group-expiration-wrap
              = f.select :exp_month, [["--",""],["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'container__content--card-form-group-expiration-wrap-select',id: "payment_card_expire_mm"
              %i.icon-arrow-bottom
              %span 月
            .container__content--card-form-group-expiration-wrap
              = f.select :exp_year, [["--",""],["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'container__content--card-form-group-expiration-wrap-select',id: "payment_card_expire_yy"
              %i.icon-arrow-bottom
              %span 年
            %ul#expire-mm-error-wrapper.container__content--card-form-group-expiration-error
              -# %li.container__content--card-form-group-expiration-error-text 必須項目です
            %ul#expire-yy-error-wrapper.container__content--card-form-group-expiration-error
              -# %li.container__content--card-form-group-expiration-error-text 必須項目です
          .container__content--card-form-group-security
            %label(for = "payment_card_security_code") セキュリティコード
            %span.container__content--card-form-group-security-require 必須
            = f.text_field :cvc, class: "container__content--card-form-group-security-input", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "card_cvc"
            %ul#security-code-error-wrapper.container__content--card-form-group-security-error
              -# %li.container__content--card-form-group-security-error-text 必須項目です
            .container__content--card-form-group-security-help
              .container__content--card-form-group-security-help-text
                %span.container__content--card-form-group-security-help-text-question ?
                %label(for = "label") カード裏面の番号とは？
                %input( type = "checkbox" id="label" class="container__content--card-form-group-security-help-text-none") 
                .container__content--card-form-group-security-help-text-content
                  %p カードの裏面をご参照ください。
                  %br/
                  =image_tag "//www-mercari-jp.akamaized.net/assets/img/signup/seq-card.png?3466462615", width:"240"
          #card_token
          = f.submit "追加する", id: "token_submit", class: "btn-default container__content--card-form-group-btn"

  =render 'users/slide_bar'

= render "items/footer"

=render 'items/selling_btn'

app/views/cards/show.html.haml
=render "items/header"
.signups-body
  - breadcrumb :payment
  =render 'categories/bread'

%main.container
  .container__content
    %section.container__content--box 
      %h2.container__content--box-head 支払い方法
      .container__content--box-inner
        %section.container__content--box-inner-center
          .container__content--box-inner-center-head
            %h3.container__content--box-inner-center-head-title クレジットカード一覧
          %ul.container__content--box-inner-center-body
            %li.container__content--box-inner-center-body-list
              %form(action ="" class="container__content--box-inner-center-body-list-type" id="" data-adyen-id ="" method ="POST")
                %figure
                  = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?3466462615', class:'container__content--box-inner-center-body-list-type-card-image', width:'49', height:'15'
                %input(type="hidden" name="__csrf_value" value="54d4a567188d7fe06b574db6f8f81d3e8984a5a7dbbeb44e0a20c2583e070ee32876445b6afe0b9a3c0c2e14fb9b3b161f6471c968dace7f3013335eece7a8d72")
                %input(type="hidden" name="card_sequence_no" value="KBrfRrCb4SwqXiW6YunmKqcc")
                .container__content--box-inner-center-body-list-type-num 
                  = "**** **** **** " + @default_card_information.last4
                .container__content--box-inner-center-body-list-type-mum 
                  - exp_month = @default_card_information.exp_month.to_s
                  - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                  = exp_month + " / " + exp_year
                  = link_to "削除する",cards_path,method: :delete,class: "container__content--box-inner-center-body-list-type-btn"

                  -# = form_tag(delete_cards_path, method: :post, id: 'card-form',  name: "inputForm") do
                  -#   %input(type="hidden" name="card_id" value="")
                  -#   %button.container__content--box-inner-center-body-list-type-btn 削除する

        .container__content--box-inner-help
          =link_to "",class:"container__content--box-inner-help-link" do
            %span 支払い方法について
            %i.icon-container__content--box-inner-help-link

  =render 'users/slide_bar'

= render "items/footer"

=render 'items/selling_btn'